import json
import os

notebook = {
 "nbformat": 4,
 "nbformat_minor": 0,
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "gpuType": "T4",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.12"
  }
 },
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🏥 MediCatalyst: 1-Click Fine-Tuning for Doctor Prescription OCR (TrOCR)\n",
    "### Domain-Adapted Vision Transformer for Indian Medical Prescriptions & Shorthand\n",
    "\n",
    "**Features:**\n",
    "1. ⚡ **Zero Setup**: Auto-configures GPU, installs tested packages (`transformers==4.46.3`), and downloads authentic cursive doctor fonts.\n",
    "2. 💊 **Indian Pharmacopoeia & Shorthand Generator**: Synthesizes 4,500 realistic training samples covering common Indian generic drugs (Jan Aushadhi / PMBJP), clinical dosages, and frequencies (`1-0-1`, `OD`, `BD`, `TID`, `SOS`).\n",
    "3. 🤖 **Microsoft TrOCR Fine-Tuning**: Vision Transformer (ViT) + RoBERTa fine-tuned with Mixed Precision (`fp16`).\n",
    "4. 📦 **One-Click Export**: Automatically zips and downloads `trocr_doctor_prescription.zip` ready for your MediCatalyst backend.\n",
    "\n",
    "--- \n",
    "**Instructions:**\n",
    "1. Go to **Runtime** > **Change runtime type** > Select **T4 GPU** > Click **Save**.\n",
    "2. Go to **Runtime** > Click **Run all** (Ctrl + F9).\n",
    "3. Sit back! In ~20-25 minutes, your browser will automatically download the fine-tuned model package."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 1: Check GPU & Install Dependencies"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Verify GPU assignment\n",
    "!nvidia-smi\n",
    "\n",
    "# 2. Install tested, stable versions to prevent upstream tokenizer bugs\n",
    "!pip install -q \"transformers==4.46.3\" datasets evaluate jiwer accelerate albumentations opencv-python-headless pillow requests rapidfuzz sentencepiece protobuf\n",
    "print('✅ Environment & Dependencies installed successfully!')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 2: Download Authentic Cursive Doctor Fonts"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import urllib.request\n",
    "\n",
    "os.makedirs('fonts', exist_ok=True)\n",
    "\n",
    "# Verified authentic cursive & doctor handwriting fonts\n",
    "font_urls = {\n",
    "    'CedarvilleCursive.ttf': 'https://raw.githubusercontent.com/google/fonts/main/ofl/cedarvillecursive/Cedarville-Cursive.ttf',\n",
    "    'ReenieBeanie.ttf': 'https://raw.githubusercontent.com/google/fonts/main/ofl/reeniebeanie/ReenieBeanie.ttf',\n",
    "    'HomemadeApple.ttf': 'https://raw.githubusercontent.com/google/fonts/main/apache/homemadeapple/HomemadeApple-Regular.ttf',\n",
    "    'Caveat.ttf': 'https://raw.githubusercontent.com/google/fonts/main/ofl/caveat/Caveat%5Bwght%5D.ttf',\n",
    "    'RockSalt.ttf': 'https://raw.githubusercontent.com/google/fonts/main/apache/rocksalt/RockSalt-Regular.ttf',\n",
    "    'ShadowsIntoLight.ttf': 'https://raw.githubusercontent.com/google/fonts/main/ofl/shadowsintolight/ShadowsIntoLight.ttf',\n",
    "    'NothingYouCouldDo.ttf': 'https://raw.githubusercontent.com/google/fonts/main/ofl/nothingyoucoulddo/NothingYouCouldDo.ttf'\n",
    "}\n",
    "\n",
    "downloaded_fonts = []\n",
    "for font_name, url in font_urls.items():\n",
    "    dest = os.path.join('fonts', font_name)\n",
    "    if not os.path.exists(dest):\n",
    "        try:\n",
    "            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})\n",
    "            with urllib.request.urlopen(req, timeout=15) as resp, open(dest, 'wb') as out_f:\n",
    "                out_f.write(resp.read())\n",
    "            downloaded_fonts.append(dest)\n",
    "            print(f'Downloaded {font_name}')\n",
    "        except Exception as e:\n",
    "            print(f'Failed {font_name}: {e}')\n",
    "    else:\n",
    "        downloaded_fonts.append(dest)\n",
    "\n",
    "print(f'\\nTotal active doctor handwriting fonts ready: {len(downloaded_fonts)}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 3: Synthetic Medical Prescription Generator (Jan Aushadhi & Indian Shorthand)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import random\n",
    "import numpy as np\n",
    "from PIL import Image, ImageDraw, ImageFont\n",
    "import albumentations as A\n",
    "import pandas as pd\n",
    "from tqdm import tqdm\n",
    "\n",
    "# Top Indian Generic Medicines (Pradhan Mantri Jan Aushadhi & Essential List)\n",
    "INDIAN_DRUGS = [\n",
    "    'Paracetamol', 'Pantoprazole', 'Azithromycin', 'Amoxicillin', 'Metformin',\n",
    "    'Cetirizine', 'Ibuprofen', 'Telmisartan', 'Atorvastatin', 'Ciprofloxacin',\n",
    "    'Levocetirizine', 'Omeprazole', 'Metoprolol', 'Amlodipine', 'Doxycycline',\n",
    "    'Montelukast', 'Ranitidine', 'Domperidone', 'Cefixime', 'Diclofenac',\n",
    "    'Ofloxacin', 'Paracetamol+Phenylephrine', 'Aceclofenac', 'Clavulanate',\n",
    "    'Losartan', 'Glimepiride', 'Vildagliptin', 'Rosuvastatin', 'Furosemide',\n",
    "    'Rabeprazole', 'B-Complex', 'Vitamin D3', 'Calcium Carbonate', 'Zinc Sulfate'\n",
    "]\n",
    "\n",
    "FORMS = ['Tab.', 'Cap.', 'Syp.', 'Inj.', 'Oint.', 'Susp.']\n",
    "DOSAGES = ['500mg', '650mg', '40mg', '20mg', '10mg', '5mg', '250mg', '1g', '10ml', '5ml', '100mg']\n",
    "FREQUENCIES = ['1-0-1', '1-0-0', '0-0-1', '1-1-1', 'OD', 'BD', 'TID', 'HS', 'SOS', 'QID']\n",
    "DURATIONS = ['x 3 days', 'x 5 days', 'x 7 days', 'x 10 days', 'x 14 days', 'x 1 month', 'x 5 d', 'for 5 days']\n",
    "INSTRUCTIONS = ['After food', 'Before food', 'Empty stomach', 'At bedtime', 'With milk', 'After meals']\n",
    "\n",
    "# Data Augmentation for paper crinkles, ink variations, blur\n",
    "augmenter = A.Compose([\n",
    "    A.GaussNoise(var_limit=(10.0, 50.0), p=0.4),\n",
    "    A.MotionBlur(blur_limit=3, p=0.3),\n",
    "    A.ColorJitter(brightness=0.2, contrast=0.2, p=0.5),\n",
    "    A.Perspective(scale=(0.01, 0.04), p=0.3)\n",
    "])\n",
    "\n",
    "def generate_prescription_line():\n",
    "    form = random.choice(FORMS)\n",
    "    drug = random.choice(INDIAN_DRUGS)\n",
    "    dosage = random.choice(DOSAGES)\n",
    "    freq = random.choice(FREQUENCIES)\n",
    "    duration = random.choice(DURATIONS)\n",
    "    instr = random.choice(INSTRUCTIONS) if random.random() > 0.4 else ''\n",
    "    \n",
    "    pattern = random.randint(1, 4)\n",
    "    if pattern == 1:\n",
    "        text = f'{form} {drug} {dosage} {freq} {duration}'\n",
    "    elif pattern == 2:\n",
    "        text = f'{drug} {dosage} {freq} ({instr}) {duration}'.strip()\n",
    "    elif pattern == 3:\n",
    "        text = f'{form} {drug} {freq} {duration}'\n",
    "    else:\n",
    "        text = f'{drug} {dosage} {freq} {duration}'\n",
    "        \n",
    "    return text.strip()\n",
    "\n",
    "def render_handwritten_image(text, font_path, width=700, height=90):\n",
    "    bg_r = random.randint(245, 255)\n",
    "    bg_g = random.randint(245, 253)\n",
    "    bg_b = random.randint(238, 248)\n",
    "    img = Image.new('RGB', (width, height), color=(bg_r, bg_g, bg_b))\n",
    "    draw = ImageDraw.Draw(img)\n",
    "    \n",
    "    font_size = random.randint(26, 36)\n",
    "    if font_path and os.path.exists(font_path):\n",
    "        font = ImageFont.truetype(font_path, font_size)\n",
    "    else:\n",
    "        font = ImageFont.load_default()\n",
    "    \n",
    "    ink = random.choice([\n",
    "        (18, 30, 110),   # Doctor ballpen blue\n",
    "        (10, 20, 90),    # Dark navy ink\n",
    "        (25, 25, 28),    # Faded black\n",
    "        (35, 35, 40)     # Gel pen black\n",
    "    ])\n",
    "    \n",
    "    x_offset = random.randint(15, 35)\n",
    "    y_offset = random.randint(15, 25)\n",
    "    draw.text((x_offset, y_offset), text, fill=ink, font=font)\n",
    "    \n",
    "    np_img = np.array(img)\n",
    "    augmented = augmenter(image=np_img)['image']\n",
    "    return Image.fromarray(augmented)\n",
    "\n",
    "os.makedirs('dataset/train', exist_ok=True)\n",
    "os.makedirs('dataset/eval', exist_ok=True)\n",
    "\n",
    "TRAIN_SAMPLES = 4000\n",
    "EVAL_SAMPLES = 500\n",
    "\n",
    "print('Generating synthetic training dataset...')\n",
    "train_records = []\n",
    "for i in tqdm(range(TRAIN_SAMPLES)):\n",
    "    text = generate_prescription_line()\n",
    "    font = random.choice(downloaded_fonts) if downloaded_fonts else None\n",
    "    img = render_handwritten_image(text, font)\n",
    "    img_filename = f'train_{i:05d}.jpg'\n",
    "    img.save(os.path.join('dataset/train', img_filename), quality=92)\n",
    "    train_records.append({'file_name': f'train/{img_filename}', 'text': text})\n",
    "\n",
    "print('Generating synthetic evaluation dataset...')\n",
    "eval_records = []\n",
    "for i in tqdm(range(EVAL_SAMPLES)):\n",
    "    text = generate_prescription_line()\n",
    "    font = random.choice(downloaded_fonts) if downloaded_fonts else None\n",
    "    img = render_handwritten_image(text, font)\n",
    "    img_filename = f'eval_{i:05d}.jpg'\n",
    "    img.save(os.path.join('dataset/eval', img_filename), quality=92)\n",
    "    eval_records.append({'file_name': f'eval/{img_filename}', 'text': text})\n",
    "\n",
    "train_df = pd.DataFrame(train_records)\n",
    "eval_df = pd.DataFrame(eval_records)\n",
    "\n",
    "train_df.to_csv('dataset/train_metadata.csv', index=False)\n",
    "eval_df.to_csv('dataset/eval_metadata.csv', index=False)\n",
    "print(f'\\nDataset ready! Train: {len(train_df)}, Eval: {len(eval_df)}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 4: Preview Generated Doctor Prescription Samples"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "\n",
    "fig, axes = plt.subplots(3, 1, figsize=(10, 6))\n",
    "for ax, row in zip(axes, train_df.head(3).itertuples()):\n",
    "    img_path = os.path.join('dataset', row.file_name)\n",
    "    ax.imshow(Image.open(img_path))\n",
    "    ax.set_title(f'Label: \"{row.text}\"', fontsize=11, loc='left', color='darkblue')\n",
    "    ax.axis('off')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 5: Setup PyTorch Dataset & TrOCR Processor (Using Stable BPE Tokenizer)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import torch\n",
    "from PIL import Image\n",
    "from torch.utils.data import Dataset\n",
    "from transformers import RobertaTokenizer, AutoImageProcessor, TrOCRProcessor, VisionEncoderDecoderModel\n",
    "\n",
    "MODEL_NAME = 'microsoft/trocr-base-handwritten'\n",
    "print(f'Loading TrOCR Processor from {MODEL_NAME}...')\n",
    "\n",
    "# Direct BPE tokenizer loading bypasses fast-conversion regressions\n",
    "tokenizer = RobertaTokenizer.from_pretrained(MODEL_NAME)\n",
    "image_processor = AutoImageProcessor.from_pretrained(MODEL_NAME)\n",
    "processor = TrOCRProcessor(image_processor=image_processor, tokenizer=tokenizer)\n",
    "\n",
    "class PrescriptionDataset(Dataset):\n",
    "    def __init__(self, root_dir, df, processor, max_target_length=64):\n",
    "        self.root_dir = root_dir\n",
    "        self.df = df\n",
    "        self.processor = processor\n",
    "        self.max_target_length = max_target_length\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.df)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        item = self.df.iloc[idx]\n",
    "        image_path = os.path.join(self.root_dir, item['file_name'])\n",
    "        image = Image.open(image_path).convert('RGB')\n",
    "        \n",
    "        pixel_values = self.processor(image, return_tensors='pt').pixel_values.squeeze()\n",
    "        labels = self.processor.tokenizer(\n",
    "            item['text'], \n",
    "            padding='max_length', \n",
    "            max_length=self.max_target_length,\n",
    "            truncation=True\n",
    "        ).input_ids\n",
    "        \n",
    "        labels = [label if label != self.processor.tokenizer.pad_token_id else -100 for label in labels]\n",
    "        \n",
    "        return {\n",
    "            'pixel_values': pixel_values,\n",
    "            'labels': torch.tensor(labels)\n",
    "        }\n",
    "\n",
    "train_dataset = PrescriptionDataset('dataset', train_df, processor)\n",
    "eval_dataset = PrescriptionDataset('dataset', eval_df, processor)\n",
    "print('✅ PyTorch Datasets compiled successfully!')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 6: Initialize TrOCR Model & CER Metric"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import evaluate\n",
    "\n",
    "print(f'Loading {MODEL_NAME} VisionEncoderDecoderModel...')\n",
    "model = VisionEncoderDecoderModel.from_pretrained(MODEL_NAME)\n",
    "\n",
    "model.config.decoder_start_token_id = processor.tokenizer.cls_token_id\n",
    "model.config.pad_token_id = processor.tokenizer.pad_token_id\n",
    "model.config.vocab_size = model.config.decoder.vocab_size\n",
    "\n",
    "model.config.eos_token_id = processor.tokenizer.sep_token_id\n",
    "model.config.max_length = 64\n",
    "model.config.early_stopping = True\n",
    "model.config.no_repeat_ngram_size = 3\n",
    "model.config.length_penalty = 1.0\n",
    "model.config.num_beams = 4\n",
    "\n",
    "cer_metric = evaluate.load('cer')\n",
    "\n",
    "def compute_metrics(pred):\n",
    "    labels_ids = pred.label_ids\n",
    "    pred_ids = pred.predictions[0] if isinstance(pred.predictions, tuple) else pred.predictions\n",
    "\n",
    "    pred_str = processor.batch_decode(pred_ids, skip_special_tokens=True)\n",
    "    labels_ids[labels_ids == -100] = processor.tokenizer.pad_token_id\n",
    "    label_str = processor.batch_decode(labels_ids, skip_special_tokens=True)\n",
    "\n",
    "    cer = cer_metric.compute(predictions=pred_str, references=label_str)\n",
    "    return {'cer': cer}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 7: Train the Model with Seq2SeqTrainer (FP16 on T4 GPU)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments, default_data_collator\n",
    "\n",
    "training_args = Seq2SeqTrainingArguments(\n",
    "    output_dir='./trocr_rx_checkpoints',\n",
    "    predict_with_generate=True,\n",
    "    evaluation_strategy='steps',\n",
    "    save_strategy='steps',\n",
    "    per_device_train_batch_size=8,\n",
    "    per_device_eval_batch_size=8,\n",
    "    fp16=True,\n",
    "    learning_rate=4e-5,\n",
    "    logging_steps=100,\n",
    "    save_steps=250,\n",
    "    eval_steps=250,\n",
    "    num_train_epochs=4,\n",
    "    warmup_ratio=0.1,\n",
    "    weight_decay=0.01,\n",
    "    save_total_limit=2,\n",
    "    report_to='none',\n",
    "    load_best_model_at_end=True,\n",
    "    metric_for_best_model='cer',\n",
    "    greater_is_better=False\n",
    ")\n",
    "\n",
    "trainer = Seq2SeqTrainer(\n",
    "    model=model,\n",
    "    tokenizer=processor.image_processor,\n",
    "    args=training_args,\n",
    "    compute_metrics=compute_metrics,\n",
    "    train_dataset=train_dataset,\n",
    "    eval_dataset=eval_dataset,\n",
    "    data_collator=default_data_collator\n",
    ")\n",
    "\n",
    "print('🚀 Starting TrOCR Fine-Tuning on Indian Doctor Prescriptions...')\n",
    "trainer.train()\n",
    "print('✅ Training Finished!')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 8: Live Evaluation & Indian Pharmacopoeia Fuzzy Matcher Demo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from rapidfuzz import process, fuzz\n",
    "import re\n",
    "\n",
    "def clinical_post_process(raw_text):\n",
    "    tokens = raw_text.split()\n",
    "    matched_drug = None\n",
    "    best_score = 0\n",
    "    \n",
    "    for token in tokens:\n",
    "        clean_t = re.sub(r'[^a-zA-Z]', '', token)\n",
    "        if len(clean_t) >= 4:\n",
    "            match, score, _ = process.extractOne(clean_t, INDIAN_DRUGS, scorer=fuzz.ratio)\n",
    "            if score > best_score and score >= 65:\n",
    "                best_score = score\n",
    "                matched_drug = match\n",
    "                \n",
    "    freq_match = re.search(r'\\b(1-0-1|1-0-0|0-0-1|1-1-1|OD|BD|TID|QID|HS|SOS)\\b', raw_text, re.IGNORECASE)\n",
    "    frequency = freq_match.group(1).upper() if freq_match else '1-0-1'\n",
    "    \n",
    "    dosage_match = re.search(r'\\b(\\d+\\s*(?:mg|g|ml))\\b', raw_text, re.IGNORECASE)\n",
    "    dosage = dosage_match.group(1) if dosage_match else 'Standard'\n",
    "    \n",
    "    return {\n",
    "        'extracted_drug': matched_drug or 'Unknown',\n",
    "        'fuzzy_confidence': f'{best_score:.1f}%',\n",
    "        'dosage': dosage,\n",
    "        'frequency': frequency\n",
    "    }\n",
    "\n",
    "print('--- TEST SET PREDICTIONS & FUZZY CORRECTION ---')\n",
    "model.eval()\n",
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "model.to(device)\n",
    "\n",
    "for i in range(5):\n",
    "    sample = eval_df.iloc[i]\n",
    "    img_path = os.path.join('dataset', sample['file_name'])\n",
    "    image = Image.open(img_path).convert('RGB')\n",
    "    pixel_values = processor(image, return_tensors='pt').pixel_values.to(device)\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        generated_ids = model.generate(pixel_values, max_length=64)\n",
    "    pred_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]\n",
    "    \n",
    "    corrected = clinical_post_process(pred_text)\n",
    "    print(f'Sample #{i+1}:')\n",
    "    print(f'   Target Label : {sample[\"text\"]}')\n",
    "    print(f'   TrOCR Output : {pred_text}')\n",
    "    print(f'   Clean Clinical Entity: {corrected[\"extracted_drug\"]} {corrected[\"dosage\"]} ({corrected[\"frequency\"]}) [Conf: {corrected[\"fuzzy_confidence\"]}]\\n')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 9: Save Weights & One-Click Download for MediCatalyst"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import shutil\n",
    "from google.colab import files\n",
    "\n",
    "OUTPUT_MODEL_DIR = './trocr_doctor_prescription'\n",
    "os.makedirs(OUTPUT_MODEL_DIR, exist_ok=True)\n",
    "\n",
    "print('Saving fine-tuned model and processor...')\n",
    "model.save_pretrained(OUTPUT_MODEL_DIR)\n",
    "processor.save_pretrained(OUTPUT_MODEL_DIR)\n",
    "\n",
    "zip_filename = 'trocr_doctor_prescription'\n",
    "print(f'Creating zip package: {zip_filename}.zip ...')\n",
    "shutil.make_archive(zip_filename, 'zip', OUTPUT_MODEL_DIR)\n",
    "\n",
    "print('\\n' + '='*60)\n",
    "print('🎉 MODEL TRAINING COMPLETE!')\n",
    "print(f'File size: {os.path.getsize(zip_filename + \".zip\") / (1024*1024):.1f} MB')\n",
    "print('Triggering automatic download to your browser...')\n",
    "print('='*60 + '\\n')\n",
    "\n",
    "try:\n",
    "    files.download(f'{zip_filename}.zip')\n",
    "except Exception as e:\n",
    "    print(f'Notice: Auto-download pop-up blocked ({e}). You can download manually from the left Files panel!')"
   ]
  }
 ]
}

out_path = r"c:\Create_websites\SIH_4\backend\ml\train_doctor_rx_trocr.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)

print(f"Jupyter Notebook successfully verified and written to {out_path}")
