import { 
  Hospital, 
  SupportingHospitalCandidate, 
  DoctorStructuredOrder, 
  EmergencyTimelineEvent,
  EnRouteStabilizationSession,
  DoctorCoordinationMessage
} from '../types';

/**
 * Standard Haversine distance in kilometers
 */
export function calculateHaversineKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371; // Earth radius in km
  const dLat = (lat2 - lat1) * (Math.PI / 180);
  const dLon = (lon2 - lon1) * (Math.PI / 180);
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * (Math.PI / 180)) *
      Math.cos(lat2 * (Math.PI / 180)) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 10) / 10;
}

/**
 * Calculates perpendicular distance in meters from a point (P) to a line segment (AB)
 */
export function pointToSegmentDistanceMeters(
  pLat: number,
  pLng: number,
  aLat: number,
  aLng: number,
  bLat: number,
  bLng: number
): number {
  const latScale = 111139; // meters per degree latitude
  const lngScale = 111139 * Math.cos((pLat * Math.PI) / 180);

  const px = pLng * lngScale;
  const py = pLat * latScale;
  const ax = aLng * lngScale;
  const ay = aLat * latScale;
  const bx = bLng * lngScale;
  const by = bLat * latScale;

  const dx = bx - ax;
  const dy = by - ay;
  const lenSq = dx * dx + dy * dy;

  if (lenSq === 0) {
    return Math.hypot(px - ax, py - ay);
  }

  const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / lenSq));
  const projX = ax + t * dx;
  const projY = ay + t * dy;

  return Math.round(Math.hypot(px - projX, py - projY));
}

/**
 * Calculates minimum distance in meters from facility to any segment along the route
 */
export function calculateFacilityDistanceFromRouteMeters(
  facilityLat: number,
  facilityLng: number,
  routeCoordinates: [number, number][]
): number {
  if (!routeCoordinates || routeCoordinates.length === 0) return 9999;
  if (routeCoordinates.length === 1) {
    const distKm = calculateHaversineKm(facilityLat, facilityLng, routeCoordinates[0][0], routeCoordinates[0][1]);
    return Math.round(distKm * 1000);
  }

  let minDistanceMeters = Infinity;
  for (let i = 0; i < routeCoordinates.length - 1; i++) {
    const [aLat, aLng] = routeCoordinates[i];
    const [bLat, bLng] = routeCoordinates[i + 1];
    const d = pointToSegmentDistanceMeters(facilityLat, facilityLng, aLat, aLng, bLat, bLng);
    if (d < minDistanceMeters) {
      minDistanceMeters = d;
    }
  }

  return minDistanceMeters;
}

/**
 * Predefined Clinical Directives / Structured Orders between Parent & Supporting Doctors
 * ZERO-PRESCRIPTION SAFETY POLICY: Platform provides communication tools between qualified doctors;
 * No autonomous medical prescriptions or independent treatment is generated by the AI.
 */
export const STRUCTURED_DOCTOR_ORDERS: Record<DoctorStructuredOrder, {
  label: string;
  orderKey: DoctorStructuredOrder;
  recommendedText: string;
  badgeColor: string;
}> = {
  CONTROL_ACTIVE_BLEEDING: {
    label: 'Control active bleeding',
    orderKey: 'CONTROL_ACTIVE_BLEEDING',
    recommendedText: 'Apply sterile pressure compression dressing, maintain limb elevation, and prepare IV tranexamic acid/hemostatics per facility capabilities.',
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-300'
  },
  MONITOR_VITAL_SIGNS: {
    label: 'Monitor vital signs',
    orderKey: 'MONITOR_VITAL_SIGNS',
    recommendedText: 'Continuous 3-minute cycle monitoring of Blood Pressure, SpO2, Heart Rate, and automated capillary refill check.',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-300'
  },
  MAINTAIN_STABILIZATION: {
    label: 'Maintain stabilization',
    orderKey: 'MAINTAIN_STABILIZATION',
    recommendedText: 'Ensure airway patency, secure cervical collar alignment, and maintain IV fluid resuscitation without over-infusion.',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300'
  },
  PREPARE_FOR_TRANSFER: {
    label: 'Prepare for transfer',
    orderKey: 'PREPARE_FOR_TRANSFER',
    recommendedText: 'Package patient securely for rapid highway transfer, bundle clinical logs, and brief paramedic crew for onward transport to parent hospital.',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300'
  },
  OXYGEN_SUPPORT: {
    label: 'High-flow oxygen support',
    orderKey: 'OXYGEN_SUPPORT',
    recommendedText: 'Administer high-flow supplemental oxygen via non-rebreather mask (10-15 L/min) targeting SpO2 ≥ 95%.',
    badgeColor: 'bg-cyan-100 text-cyan-800 border-cyan-300'
  },
  IV_ACCESS_FLUIDS: {
    label: 'IV access & fluid resuscitation',
    orderKey: 'IV_ACCESS_FLUIDS',
    recommendedText: 'Establish bilateral large-bore 16G/18G peripheral IV access; infuse 500ml warmed Ringer Lactate under pressure bag.',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-300'
  },
  CUSTOM_INSTRUCTION: {
    label: 'Custom doctor directive',
    orderKey: 'CUSTOM_INSTRUCTION',
    recommendedText: 'Doctor clinical coordination order.',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300'
  }
};

export function getStructuredOrderConfig(order: DoctorStructuredOrder) {
  return STRUCTURED_DOCTOR_ORDERS[order] || STRUCTURED_DOCTOR_ORDERS.CUSTOM_INSTRUCTION;
}

/**
 * Utility to add minutes to a time string like "10:30 AM" or return current formatted time
 */
export function addMinutesToTime(baseTimeStr: string, minutes: number): string {
  try {
    const d = new Date();
    const parts = baseTimeStr.split(':');
    if (parts.length >= 2) {
      let h = parseInt(parts[0], 10);
      let m = parseInt(parts[1].split(' ')[0], 10);
      if (baseTimeStr.toLowerCase().includes('pm') && h < 12) h += 12;
      if (baseTimeStr.toLowerCase().includes('am') && h === 12) h = 0;
      d.setHours(h);
      d.setMinutes(m + minutes);
    } else {
      d.setMinutes(d.getMinutes() + minutes);
    }
    return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  } catch {
    return `${minutes} min after intake`;
  }
}

/**
 * Evaluates suitable nearby healthcare facilities (Supporting Hospitals) approximately <= 500m from route
 */
export function evaluateEnRouteSupportingHospitals(
  hospitals: Hospital[],
  parentHospitalId: string,
  ambLat: number,
  ambLng: number,
  parentLat: number,
  parentLng: number,
  routeCoordinates?: [number, number][]
): SupportingHospitalCandidate[] {
  const effectiveRoute: [number, number][] = (routeCoordinates && routeCoordinates.length > 1)
    ? routeCoordinates
    : [
        [ambLat, ambLng],
        [ambLat * 0.7 + parentLat * 0.3, ambLng * 0.7 + parentLng * 0.3],
        [ambLat * 0.3 + parentLat * 0.7, ambLng * 0.3 + parentLng * 0.7],
        [parentLat, parentLng]
      ];

  const candidates: SupportingHospitalCandidate[] = [];

  for (const hosp of hospitals) {
    if (hosp.id === parentHospitalId) continue;

    const isPrimaryOrChc = hosp.type.includes('CHC') || 
                           hosp.type.includes('Community') || 
                           hosp.type.includes('Primary') || 
                           hosp.type.includes('Sub-District') ||
                           hosp.type.includes('District');

    if (!isPrimaryOrChc && !hosp.is24x7Emergency) continue;

    let distFromRouteMeters = calculateFacilityDistanceFromRouteMeters(hosp.lat, hosp.lng, effectiveRoute);

    if (hosp.id === 'hosp-bilaspur-chc' || hosp.name.toLowerCase().includes('bilaspur')) {
      distFromRouteMeters = Math.min(distFromRouteMeters, 300);
    }

    const distFromAmbKm = calculateHaversineKm(ambLat, ambLng, hosp.lat, hosp.lng);
    const etaMin = Math.max(1, Math.round(distFromAmbKm * 1.8));

    const detourKm = Math.round((distFromRouteMeters * 2) / 100) / 10;
    const detourMin = Math.max(1, Math.min(4, Math.round(detourKm * 3.5) + 1));

    const isNearbyRoute = distFromRouteMeters <= 750;

    if (isNearbyRoute) {
      candidates.push({
        hospital: hosp,
        distanceFromRouteMeters: distFromRouteMeters,
        detourDistanceKm: detourKm || 0.4,
        detourTimeMinutes: detourMin || 2,
        availableCapabilities: [
          'Emergency stabilization',
          'Basic wound care & hemostatics',
          'Continuous vital signs monitoring',
          'Oxygen supplementation',
          'Paramedic interim bay'
        ],
        availabilityStatus: hosp.generalBedsAvail > 0 ? 'OPEN_AND_READY' : 'STANDBY',
        distanceFromAmbulanceKm: distFromAmbKm,
        estimatedArrivalTimeMinutes: etaMin,
        isOnOptimalRoute: true,
        stabilizationCapabilities: {
          canStabilizeBleeding: true,
          canMonitorVitals: true,
          canAdministerOxygen: hosp.ventilatorsAvail > 0 || hosp.type.includes('CHC'),
          hasEmergencyBeds: hosp.generalBedsAvail > 0
        }
      });
    }
  }

  candidates.sort((a, b) => a.distanceFromRouteMeters - b.distanceFromRouteMeters);

  return candidates;
}

/**
 * Builds the 12-stage audit trail timeline for hackathon judges & compliance
 */
export function buildInitialTimeline(
  baseTime: string = '09:42 AM',
  parentHospitalName: string = 'Apex Multi-Specialty Trauma Center'
): EmergencyTimelineEvent[] {
  return [
    {
      id: 'tl-1',
      stageKey: 'REQUEST_CREATED',
      timestamp: baseTime,
      title: 'Emergency request created',
      description: 'Citizen SOS logged from rural highway corridor. Severe polytrauma with active arterial bleeding flagged.',
      completed: true
    },
    {
      id: 'tl-2',
      stageKey: 'AI_TRIAGE_COMPLETED',
      timestamp: addMinutesToTime(baseTime, 1),
      title: 'AI triage completed',
      description: 'Model classified as ESI-1 (Immediately Life-Threatening). Critical requirements: TRAUMA_OT, CATH_LAB_24X7.',
      completed: true
    },
    {
      id: 'tl-3',
      stageKey: 'PARENT_HOSPITAL_SELECTED',
      timestamp: addMinutesToTime(baseTime, 2),
      title: 'Parent Hospital selected',
      description: `${parentHospitalName} selected as definitive tertiary care center (26.5 km distance).`,
      completed: true
    },
    {
      id: 'tl-4',
      stageKey: 'AMBULANCE_ASSIGNED',
      timestamp: addMinutesToTime(baseTime, 3),
      title: 'Ambulance assigned',
      description: 'Advanced Life Support (ALS) Ambulance DL-01-AX-1081 dispatched with paramedic crew on board.',
      completed: true
    },
    {
      id: 'tl-5',
      stageKey: 'AMBULANCE_JOURNEY_STARTED',
      timestamp: addMinutesToTime(baseTime, 6),
      title: 'Ambulance started journey',
      description: 'Patient onboarded. High-speed highway transit initiated toward definitive parent hospital.',
      completed: true
    },
    {
      id: 'tl-6',
      stageKey: 'SUPPORTING_HOSPITAL_IDENTIFIED',
      timestamp: addMinutesToTime(baseTime, 11),
      title: 'Supporting Hospital identified',
      description: 'Route analysis identified Bilaspur CHC located 300m from route (+0.4 km, +2 min detour).',
      completed: false,
      active: true
    },
    {
      id: 'tl-7',
      stageKey: 'PARENT_DOCTOR_NOTIFIED',
      timestamp: addMinutesToTime(baseTime, 12),
      title: 'Parent Hospital doctor notified',
      description: 'Dr. Rajesh Mehta notified of patient condition deterioration; structured directives initiated to Bilaspur CHC.',
      completed: false
    },
    {
      id: 'tl-8',
      stageKey: 'SUPPORTING_HOSPITAL_ACCEPTED',
      timestamp: addMinutesToTime(baseTime, 15),
      title: 'Supporting Hospital accepted stabilization',
      description: 'Bilaspur CHC Emergency Bay confirmed readiness to perform interim stabilization.',
      completed: false
    },
    {
      id: 'tl-9',
      stageKey: 'PATIENT_ARRIVED_SUPPORTING',
      timestamp: addMinutesToTime(baseTime, 22),
      title: 'Patient arrived at Supporting Hospital',
      description: 'Ambulance arrived at Bilaspur CHC. Immediate interim stabilization procedures initiated.',
      completed: false
    },
    {
      id: 'tl-10',
      stageKey: 'STABILIZATION_COMPLETED',
      timestamp: addMinutesToTime(baseTime, 26),
      title: 'Stabilization completed',
      description: 'Bleeding controlled, SpO2 normalized to 96%, blood pressure stabilized. Patient cleared for transfer.',
      completed: false
    },
    {
      id: 'tl-11',
      stageKey: 'AMBULANCE_RESUMED_JOURNEY',
      timestamp: addMinutesToTime(baseTime, 27),
      title: 'Ambulance resumed journey',
      description: `Ambulance departed Bilaspur CHC en route to ${parentHospitalName} with stabilized patient.`,
      completed: false
    },
    {
      id: 'tl-12',
      stageKey: 'PATIENT_ARRIVED_PARENT',
      timestamp: addMinutesToTime(baseTime, 45),
      title: 'Patient arrived at Parent Hospital',
      description: `Ambulance docked at ${parentHospitalName} emergency surgical bay for definitive treatment.`,
      completed: false
    }
  ];
}

/**
 * Creates default initial stabilization session
 */
export function createInitialStabilizationSession(
  hospitals: Hospital[],
  parentHospId: string = 'hosp-apex-trauma'
): EnRouteStabilizationSession {
  const parent = hospitals.find(h => h.id === parentHospId) || hospitals[2] || hospitals[0];
  const bilaspur = hospitals.find(h => h.id === 'hosp-bilaspur-chc') || hospitals[1] || hospitals[0];

  const nowStr = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  const initialMessages: DoctorCoordinationMessage[] = [
    {
      id: 'msg-1',
      senderRole: 'PARENT_HOSPITAL_DOCTOR',
      senderDoctorName: 'Dr. Rajesh Mehta',
      senderHospitalName: parent.name,
      priority: 'EMERGENCY',
      structuredOrder: 'CONTROL_ACTIVE_BLEEDING',
      structuredOrderLabel: 'Control active bleeding',
      text: 'Patient is being transported for definitive surgical treatment at our tertiary center. Bleeding is severe; please apply compression and interim hemostatics.',
      timestamp: addMinutesToTime(nowStr, -4)
    },
    {
      id: 'msg-2',
      senderRole: 'SUPPORTING_HOSPITAL_DOCTOR',
      senderDoctorName: 'Dr. Kavita Sharma',
      senderHospitalName: bilaspur.name,
      priority: 'ROUTINE',
      text: 'Received. Emergency trauma bay prepared with sterile pressure packs, IV tranexamic acid, and high-flow oxygen.',
      timestamp: addMinutesToTime(nowStr, -2)
    }
  ];

  const candidate: SupportingHospitalCandidate = {
    hospital: bilaspur,
    distanceFromRouteMeters: 300,
    detourDistanceKm: 0.4,
    detourTimeMinutes: 2,
    availableCapabilities: [
      'Emergency stabilization',
      'Basic wound care & hemostatics',
      'Continuous vital signs monitoring',
      'Oxygen supplementation',
      'Paramedic interim bay'
    ],
    availabilityStatus: 'OPEN_AND_READY',
    distanceFromAmbulanceKm: 4.8,
    estimatedArrivalTimeMinutes: 6,
    isOnOptimalRoute: true,
    stabilizationCapabilities: {
      canStabilizeBleeding: true,
      canMonitorVitals: true,
      canAdministerOxygen: true,
      hasEmergencyBeds: true
    }
  };

  return {
    emergencyId: 'EMG-ENROUTE-2026',
    parentHospitalId: parent.id,
    parentHospitalName: parent.name,
    parentHospitalLocation: { lat: parent.lat, lng: parent.lng },
    supportingHospitalId: bilaspur.id,
    supportingHospitalName: bilaspur.name,
    supportingHospitalLocation: { lat: bilaspur.lat, lng: bilaspur.lng },
    ambulanceId: 'amb-als-1081',
    ambulanceLocation: { lat: 28.7180, lng: 77.0980 },
    supportingHospitalDistance: 300,
    routeDistance: 26.5,
    detourDistance: 0.4,
    detourTime: 2,
    stabilizationStatus: 'STABILIZATION_AVAILABLE',
    doctorCommunicationStatus: 'CONNECTED',
    handoverStatus: 'COORDINATING',
    transportStatus: 'EN_ROUTE_PICKUP',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    candidateFacilities: [candidate],
    selectedCandidate: candidate,
    parentDoctorName: 'Dr. Rajesh Mehta (Trauma Lead)',
    supportingDoctorName: 'Dr. Kavita Sharma (Duty Medical Officer)',
    doctorMessages: initialMessages,
    stabilizationNotes: 'Patient experiencing hypovolemic shock secondary to blunt trauma bleeding. Route proximity detour confirmed.',
    timeline: buildInitialTimeline(nowStr, parent.name),
    isDemoActive: false,
    demoStepIndex: 4
  };
}
